# Generated by Django 4.0.4 on 2025-02-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorsAppointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsappointment',
            name='patient_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
