# Generated by Django 4.0.4 on 2025-02-07 17:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0015_remove_doctor_email'),
        ('DoctorsAppointment', '0002_doctorsappointment_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsappointment',
            name='dr_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Doctor.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorsappointment',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctorsappointment',
            name='patient_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctorsappointment',
            name='patient_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
