# Generated by Django 4.0.4 on 2025-02-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorsAppointment', '0003_alter_doctorsappointment_dr_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsappointment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='doctorsappointment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='doctorsappointment',
            name='transaction_id',
        ),
    ]
