# Generated by Django 4.0.4 on 2025-02-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phar_name', models.CharField(blank=True, max_length=500, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('license_num', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('address', models.CharField(help_text='Specific area', max_length=100)),
                ('contact_num', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('opening_h', models.TimeField(blank=True, null=True)),
                ('closing_h', models.TimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
