# Generated by Django 4.0.4 on 2025-03-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physiotherapist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiotherapist',
            name='day_of_service',
            field=models.JSONField(blank=True, help_text='Days available for service (as an array)', null=True),
        ),
        migrations.AlterField(
            model_name='physiotherapist',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('F', 'F')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='physiotherapist',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bkash', 'bkash'), ('nogod', 'nogod'), ('rocket', 'rocket')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='physiotherapist',
            name='time_of_service',
            field=models.CharField(blank=True, help_text='Time available for service (as a string)', max_length=255, null=True),
        ),
    ]
