# Generated by Django 4.0.4 on 2025-03-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physiotherapist', '0002_alter_physiotherapist_day_of_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiotherapist',
            name='specialty',
            field=models.CharField(blank=True, help_text='Area of specialization', max_length=100, null=True),
        ),
    ]
