# Generated by Django 4.0.4 on 2025-03-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physiotherapist', '0003_alter_physiotherapist_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiotherapist',
            name='specialty',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
    ]
