# Generated by Django 4.0.4 on 2024-11-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('degree', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('day_of_service', models.CharField(help_text='Day(s) available for service', max_length=20)),
                ('time_of_service', models.TimeField()),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'cash'), ('Card', 'card'), ('Online Transfer', 'online Transfer'), ('Other', 'other')], max_length=20)),
                ('payment_method_number', models.CharField(blank=True, max_length=15, null=True)),
                ('nid', models.CharField(max_length=20, unique=True)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
            ],
        ),
    ]
