# Generated by Django 4.0.4 on 2024-11-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
