# Generated by Django 4.0.4 on 2024-11-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_remove_doctor_available_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dr_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
