# Generated by Django 4.0.4 on 2025-02-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_doctor_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_approved',
        ),
    ]
