# Generated by Django 4.0.4 on 2025-02-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0009_doctor_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
