# Generated by Django 4.0.4 on 2025-02-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0014_remove_doctor_user_doctor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
    ]
