# Generated by Django 4.0.4 on 2025-03-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0016_alter_doctor_day_of_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bkash', 'bkash'), ('nogod', 'nogod'), ('rocket', 'rocket')], max_length=20, null=True),
        ),
    ]
